### PR TITLE
fixes a problem where calling `init.bat /v` would not work correctly

### PR DESCRIPTION
**Pull request by DRSDavidSoft**
This seems to fix a problem where calling `init.bat /v` directly from any directory would fail to set the `%CMDER_ROOT%` variable if `%ConEmuDir%` is also not set (e.g. not using ConEmu with Cmder.)

fixed_init_verb

### CODE REVIEW

**Comment by DRSDavidSoft** [comment]
@daxgames would you also reviw this PR too?

**Comment by daxgames** [comment]
@DRSDavidSoft I cannot duplicate the issue we saw when you ran it, so not sure what happened.  I made additional changes last night.  I now differentiate between verbose "/v" and debug "/d"output.  Could you try again with my code base without your changes and test with both switches.

**Comment by DRSDavidSoft** [comment]
@daxgames I can not confirm that calling [`init.bat`](https://raw.githubusercontent.com/daxgames/cmder/init_args/vendor/init.bat) with `/v` passed work on my machine, and the reason is quite obvious – the [`%0`](https://github.com/daxgames/cmder/blob/init_args/vendor/init.bat#L65) points out to the `/v` or `/d` somehow on my machine. (IMO, it's related to the `shift` making the arguments order go out of the required order.)
This patch fixes the problem though :)

BTW, how to reproduce:
1. Put `init.bat` in `C:\somedir\cmder\vendor\init.bat`
2. <kbd>Win+R</kbd> → `cmd` and issue: `cd /d "D:\Path\to\another\drive\With Spaces\etc"`
3. Issue **exactly** this command:
`C:\somedir\cmder\vendor\init.bat /v`

...and you can see the problem.

Note that if you issue `C:\somedir\cmder\vendor\init.bat` first before issuing `C:\somedir\cmder\vendor\init.bat /v`, the `%CMDER_ROOT%` is already defined, so it won't bother with the `%~dp0\..` variable.

I hope I've provided an in-depth analysis, let me know if managed to reproduce this with the current commit of `init.bat`.

**Comment by daxgames** [comment]
@DRSDavidSoft So you are testing the execution if `init.bat /d` outside cmder.exe and outside conemu.exe.  I was able to reproduce with your steps.

I would have never tested execution of init.bat outside cmder,exe or conemu.exe as it was never designed to be run this way.  You are correct the shift is affecting the setting of cmder_root so I am simply going to move the setting of cmder_root above the command line parsing code which is where it should be anyway.

I am rejecting this PR since it will work by just reordering the original code.

**Comment by DRSDavidSoft** [comment]
@daxgames thanks for verifying and reordering the logic, honestly it makes more sense that my patch.

But I want to point out that [many resources](https://www.google.com/search?q=cmder+vscode) instruct users to call `cmd /c init.bat` to run [Cmder within VSCode](https://github.com/cmderdev/cmder/issues/1646#issuecomment-368328402), or other integrated terminals than ConEmu. I personally love Maximus5's work, but Cmder technically works just as awesomely with other terminal emulators.

However, the main point is if init.bat works on its own, and we can order it to not have issues with arguments passed, IMHO it's more elegant to have it too.

Thanks for your help!

**Comment by daxgames** [comment]
@DRSDavidSoft Good to know about those other uses.  I have never tried to run it separately.  THanks for being persistent!

**Pull request closed without merging**
