### PR TITLE
Added `lib_git.cmd`

### PR DESCRIPTION
**Pull request by DRSDavidSoft**
## Lib it: **Git Version Comparing**

**Status:** Needs to be tested and edited before merging.
Please do _not_ merge until the edits are committed.

### CODE REVIEW

**Comment by daxgames** [comment]
@DRSDavidSoft you want me to merge this as is and fill in the docs in the subs or you want to do it?

**Comment by DRSDavidSoft** [comment]
@daxgames I'd appreciate you writing the docs, but please wait first before I add some more commits here so I'll be sure it's final. Thanks!

**Comment by daxgames** [comment]
Ok not sure what else it needs because it does already work.  Waiting for your reply.

**Comment by DRSDavidSoft** [comment]
@daxgames Done. Yeah, it was just [some minor edits](https://github.com/DRSDavidSoft/cmder/commit/b86cf9f22e4de215c59326818beb4003df2fdac5#diff-58ef2dd68a566c2381fe971fe0011070) that I wanted to do before you merged them. Could you fill the docs for all the subs now?

Great work BTW, "Libbing" Cmder has been nicely done!

**Comment by daxgames** [comment]
Cool will do.  I am getting close on fixing cmder.exe.  I am not a c++ guy so it takes me a while...

**Pull request merged**
