### PR TITLE
implements recursive `/bin` path enhancing.

### PR DESCRIPTION
**Pull request by DRSDavidSoft**
This PR implements feature requested at: https://github.com/cmderdev/cmder/issues/1624 (if @Stanzilla also approves it.)

If you have another or better idea on how to implement it (or others disagree with this) you can close this PR.

### CODE REVIEW

**Comment by daxgames** [comment]
I have tried to write this response like 5 times.  Sorry for the delay.

@DRSDavidSoft and @Stanzilla I like this but it could be dangerous, causing truncated a path if the path gets too long, so it should not be a default.

A better approach would be to set a default depth limit of 1 which only adds the currently passed directory.  If depth limit, set by an init.bat command line argument, is greater than 1 then add subdirs to that depth.  This way if a user wants it he/she can turn it on and if it breaks its on them and it's configurable.

Maybe even look for exe/bat/cmd files in a folder be for adding it to the path and not doing it if none exist.

This should also be done for the `%cmder_user_bin%`.

Cmder already has the ability to do this through other user init scripts in `%cmder_root%\config` and `%cmder_root%\config\profile.d` in a much more targeted way by adding specific dirs to these locations.

We could maybe even write the :enhance_path/:enhance_path_recursive logic as separate script `%cmder_root%\bin` so it could be used by `init.bat` and the user init scripts I mentioned above.

**Comment by DRSDavidSoft** [comment]
@daxgames No worries regarding the delay.

I agree with your point on path getting truncated, I learned about this windows limitation the hard way after some tests.

I also think we should extract any subroutines (currently, both git version comparison and path enhancing to external scripts and only call them from init.bat.

Also, many aspects of init.bat should be configurable from the config directory. e. g. : path depth and force use vendored binaries.

**Comment by Stanzilla** [comment]
I think a depth limit of one would be a sensible default

**Comment by daxgames** [comment]
I can pull the enhance_path logic into a separate script in %cmder_root%\bin as a part of my PR.  @DRSDavidSoft do you want to develop the depth limit code or do you want me to just merge this into mine before I pull the logic out int a separate script.  Then either of us could write it into the external script?

**Comment by DRSDavidSoft** [comment]
@daxgames It works both ways, IMO it's better if you merge & test this before we write the depth limiting logic. Also can you work on the config part? Something like `set PATH_DEPTH_LIMIT=1` which is defined _before_ `init.bat` is called. That way, you can replace all instances of where `:enhance_path` van be changed to `:enhance_path_recursive`.

On another note, it would be cool if we can change the content of config via comment line, like `cmder /set config.path_depth=1` or something like that. (If that's desirable, I can work on a logic to read & write to the config file, but first all the devs need to agree on the design of the config.  If @Stanzilla agrees, this should be opened in a new issue/PR.)

For now, if you accept this PR, please merge and close it so we can close https://github.com/cmderdev/cmder/issues/1624, and after coming up with the logic for config, we can implement the depth limiter. I can think of this:

```
	...
	set DEPTH=%~2
	if %DEPTH% LEQ %LIMIT% (
		set /a DEPTH=%DEPTH% + 1
		call :add_recursive %SOME_DIRECTORY %DEPTH%
	) else (
		rem call :debug-output  :add_recursive - Reached depth limit

		:: or always show warning
		echo. WARNING: found more than %LIMIT% subdirectories in %PARENT%, ignoring...
	)
```

**Pull request merged**
